#This playbook operates on a network accessible Windows Server and checks the following services:
#---> EventLog (Windows Event Log)
#---> wuauserv (Windows Update)

#The following variables need to be defined in Ansible Tower or Ansible Engine Playbook/Inventory
#ansible_connection: winrm
#ansible_password: ******************
#ansible_port: 5986
#ansible_user: ******************
#ansible_winrm_operation_timeout_sec: 60
#ansible_winrm_read_timeout_sec: 70
#ansible_winrm_server_cert_validation: ignore
#ansible_winrm_transport: basic

#This playbook uses an Azure dynamic inventory on Ansible Tower
#Logic is included to only operate on a hostname called 'winabc' which can be removed

---
- name: SERVICE CHECK, PRINT AND RESTORE
  hosts: all
  gather_facts: false

  tasks:
  - name: CHECK IF WINDOWS UPDATE IS RUNNING
    win_service:
      name: wuauserv
    register: wuauserv_info
    when: inventory_hostname == 'winabc'

  - name: CHECK IF WINDOWS EVENTLOG IS RUNNING
    win_service:
      name: EventLog
    register: EventLog_info
    when: inventory_hostname == 'winabc'

  - name: PRINT SERVICE STATE INFO
    debug:
       msg: Host {{inventory_hostname}} Service {{wuauserv_info.display_name}} is {{wuauserv_info.state}}
    when: inventory_hostname == 'winabc'

  - name: PRINT SERVICE STATE INFO
    debug:
       msg: Host {{inventory_hostname}} Service {{EventLog_info.display_name}} is {{EventLog_info.state}}
    when: inventory_hostname == 'winabc'

  - name: START WINDOWS UPDATE IF NECESSARY
    win_service:
      name: wuauserv
      state: started
    when:
      - inventory_hostname == 'winabc'
      - wuauserv_info.state == 'stopped'

  - name: START WINDOWS EVENTLOG IF NECESSARY
    win_service:
      name: EventLog
      state: started
    when:
      - inventory_hostname == 'winabc'
      - EventLog_info.state == 'stopped'
