---
- name: CREATE AZURE RHEL 7.6 SERVER
  connection: local
  gather_facts: no
  hosts: localhost
  vars:
    my_resource_group: MyResourceGroup

  tasks:
  - name: CREATE PUBLIC IP ADDRESS
    azure_rm_publicipaddress:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      resource_group: myResourceGroup
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: DISPLAY PUBLIC IP ADDRESS
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: CREATE SSH ALLOWING SECURITY GROUP
    azure_rm_securitygroup:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      resource_group: myResourceGroup
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: CREATE VNIC
    azure_rm_networkinterface:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      resource_group: myResourceGroup
      name: myNIC
      virtual_network: demo-VN
      subnet: demo-SN
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: CREATE VM
    azure_rm_virtualmachine:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      resource_group: myResourceGroup
      name: "{{ my_vm_name }}"
      vm_size: Standard_B2s
      admin_username: richard
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/richard/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtVxBQ5BD/jPeT5PzGQ48Y/Hc5sfhXmZQGbhhZu6mfewczcTWidIu1OH1tzG01SIYICc8iQv/GiEyta1pzDpLu/bLbxIdLCDOp56SjbkYN+OUwIaeltNOt9hdbReX4PA5qbozj8XLUJE8VWnpzdCRSA+xn0nrsF+36uWUPWVhtCopo0TAEYjgMb2mRmOG/23mbu3wyy8kKGxmYrgjwQfmQ3wP347XlpW93ZWO+IFjtn54NkT3+vFT931xogcpqfyURr9SDi8ohCrtvtwOGIMTU1oFzQTxRJp/B74XTYkcsxm9G5UaO8kjucTFAUItNpKkbuEYDP/37UoO7+aZs2aAl richard@at1
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.6'
        version: latest
