---
- name: AZURE RHEL 7.6 SERVER
  connection: local
  gather_facts: no
  hosts: localhost
  vars:
    my_resource_group: MyResourceGroup

  tasks:
  - name: PROVSION VIRTUAL HOST
  - name: Create public IP address
    azure_rm_publicipaddress:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      resource_group: myResourceGroup
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      resource_group: myResourceGroup
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      resource_group: myResourceGroup
      name: myNIC
      virtual_network: demo-VN
      subnet: demo-SN
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      resource_group: myResourceGroup
      name: "{{ my_vm_name }}"
      vm_size: Standard_B2s
      admin_username: richard
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/richard/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSVS675Hu7wpHzxfbfsi75f2LS/AMR8jAgIXTFd6VtllFwJGJ1LYMKJc7HHFfwWuTBbzhyY39mDddfKG2qJa5PGZkdPOcaQFNkX+l3EWmBEyi8qq3wBbZUvJKh3GKuzj5rJayUnTOmaV9iCipJSRQV9AJSePg6/9bevPHCE/LX/kEnSATKZZ1/sZFudXCurl34V2hTX03a0F9wKw8prDf2JUBLvPCT3gsdzEInea1ftQZob1rRkDZ83UjplgyCccFvHoPPYNzrlHo+RqdrUoNRMOPTRpjK0xsH5Vf5ZHhBHCIR8w/RrB3sOXJimIaC1dm5qQtMGMI8weyuvOEo9KtX
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.6'
        version: latest
